config/routes.rb
Rails.application.routes.draw do
  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''         # remember bracket '()'
  end

  resources :comments

  resources :articles, concerns: :paginatable

  resources :authors
  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :author
  has_many :comments


  include PgSearch
  pg_search_scope :search, against:[:name, :content],
                  using: {tsearch:{dictionary:'english'}},
                  associated_against: {author: :name, comments: [:name, :content]}
                  # ignoring: :accents

  scope :text_search, ->(query)do
    if query.present?
      # rank = <<-RANK
      #   ts_rank(to_tsvector(name), to_tsquery(#{sanitize(query)})) +
      #   ts_rank(to_tsvector(content), to_tsquery(#{sanitize(query)}))
      # RANK
      # where("name @@ :q or content @@ :q", q: query)
      rank = <<-RANK
        ts_rank(to_tsvector(name), plainto_tsquery(#{sanitize(query)}))
      RANK
      query = query
      where("name @@ :q or content @@ :q", q: query).order("#{rank} desc")
    end
  end
end

app/models/author.rb
class Author < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.includes(:author).search(params[:search]).page(params[:page]).per(3)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:author_id, :name, :content, :published_at)
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:article_id, :name, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.haml
= simple_form_for(@article) do |f|
  = f.error_notification

  .form-inputs
    = f.association :author
    = f.input :name
    = f.input :content
    = f.input :published_at

  .form-actions
    = f.button :submit

app/views/articles/edit.html.haml
.page-header
  = link_to articles_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @article, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing article

= render 'form'

app/views/articles/index.html.haml
.page-header
  = link_to new_article_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Article
  %h1 Listing articles

= form_tag articles_path, method: :get do
  = text_field_tag :search, params[:search]
  = submit_tag 'Search'
= paginate @articles
.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Author
        %th Name
        %th Content
        %th Published at
        %th
        %th
        %th

    %tbody
      - @articles.each do |article|
        %tr
          %td= article.author.name
          %td= article.name
          %td= article.content
          %td= article.published_at
          %td= link_to 'Show', article
          %td= link_to 'Edit', edit_article_path(article)
          %td= link_to 'Destroy', article, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/articles/new.html.haml
.page-header
  = link_to articles_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New article

= render 'form'

app/views/articles/show.html.haml
.page-header
  = link_to articles_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_article_path(@article), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show article

%dl.dl-horizontal
  %dt Author:
  %dd= @article.author
  %dt Name:
  %dd= @article.name
  %dt Content:
  %dd= @article.content
  %dt Published at:
  %dd= @article.published_at

app/views/authors/_form.html.haml
= simple_form_for(@author) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/authors/edit.html.haml
.page-header
  = link_to authors_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @author, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing author

= render 'form'

app/views/authors/index.html.haml
.page-header
  = link_to new_author_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Author
  %h1 Listing authors

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th
        %th
        %th

    %tbody
      - @authors.each do |author|
        %tr
          %td= author.name
          %td= link_to 'Show', author
          %td= link_to 'Edit', edit_author_path(author)
          %td= link_to 'Destroy', author, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/authors/new.html.haml
.page-header
  = link_to authors_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New author

= render 'form'

app/views/authors/show.html.haml
.page-header
  = link_to authors_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_author_path(@author), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show author

%dl.dl-horizontal
  %dt Name:
  %dd= @author.name

app/views/comments/_form.html.haml
= simple_form_for(@comment) do |f|
  = f.error_notification

  .form-inputs
    = f.association :article
    = f.input :name
    = f.input :content

  .form-actions
    = f.button :submit

app/views/comments/edit.html.haml
.page-header
  = link_to comments_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @comment, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing comment

= render 'form'

app/views/comments/index.html.haml
.page-header
  = link_to new_comment_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Comment
  %h1 Listing comments

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Article
        %th Name
        %th Content
        %th
        %th
        %th

    %tbody
      - @comments.each do |comment|
        %tr
          %td= comment.article
          %td= comment.name
          %td= comment.content
          %td= link_to 'Show', comment
          %td= link_to 'Edit', edit_comment_path(comment)
          %td= link_to 'Destroy', comment, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/comments/new.html.haml
.page-header
  = link_to comments_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New comment

= render 'form'

app/views/comments/show.html.haml
.page-header
  = link_to comments_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_comment_path(@comment), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show comment

%dl.dl-horizontal
  %dt Article:
  %dd= @comment.article
  %dt Name:
  %dd= @comment.name
  %dt Content:
  %dd= @comment.content

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    %title my_343_pg_search

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{:type => "button", :data => {:toggle => "collapse", :target => "#navbar"}, :aria => {:expanded => "false", :controls => "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Project name", "#", :class => "navbar-brand"
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              %a{:href => "#"} Home
            %li
              %a{:href => "#about"} About
            %li
              %a{:href => "#contact"} Contact
    .container
      - flash.each do |name, msg|
        = content_tag :div, :class => "alert alert-#{%w[alert error].include?(name.to_s) ? "danger" : "success" } alert-dismissable", :role => "alert" do
          %button.close{:type => "button", :data => {:dismiss => "alert"} }
            %span{:aria => {:hidden => "true"} } &times;
            %span.sr-only Close
          = msg
      = yield